### ISSUE TITLE
cellbg doesn't work if the wrap-Plugin is involved in the same row

### ISSUE THREAD

**Issue by aloishockenschlohe** [dr4Ke/cellbg#16]
If in the same row of the table the popular plugin "wrap" is involved, the cellbg tag seems not to be interpreted. 

Latest wrap-Plugin (Last updated on 2018-04-22).
Latest cellbg-Plugin (Last updated on 2013-10-09).

**Comment by dr4Ke** [comment]
I'm sorry, I don't use this plugin anymore and don't have much time to look at this.

**Comment by aloishockenschlohe** [comment]
No problem. :-)
Fixed the issue. I am leaving a pull request.
